title = "Loomhigh"
baseURL = "http://loomhigh.github.io"
languageCode = "en-au"
disablePathToLower = true
pagerSize = 50
enableGitInfo = true
enableRobotsTXT = true

[params]
github_username = "loomhigh"

[markup.goldmark.renderer]
unsafe = true

#[permalinks]
#minutes = "/events/committee/:year/:month-:day/"
