title = "Loomhigh"
baseURL = "http://loomhigh.github.io"
languageCode = "en-au"
disablePathToLower = true
paginate = 50
enableGitInfo = true
enableRobotsTXT = true

[params]
github_username = "loomhigh223555"

#[markup.goldmark.renderer]
#unsafe = true

#[permalinks]
#minutes = "/events/committee/:year/:month-:day/"
